### ISSUE TITLE
Auto version updates FileListener anomalies

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-studio#56]
Issues with automatic update of ./mdw/versions files when assets are changed locally:
 - On Windows, CR/LFs are inserted into versions file.
 - Git pull from within IntelliJ with uncommitted local changes can trigger the following exception:
  ```
    org.eclipse.jgit.errors.MissingObjectException: Missing unknown 71c93e8b9d64e7a3b9193dde6dbc9825210a9542
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:163)
    at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
    at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
    at com.centurylink.mdw.dataaccess.file.VersionControlGit.readFromCommit(VersionControlGit.java:707)
    at com.centurylink.mdw.dataaccess.file.VersionControlGit.readFromHead(VersionControlGit.java:730)
    at com.centurylink.mdw.studio.proj.AssetFileListener.after(AssetFileListener.kt:53)
  ```

**Comment by jbrojdeCTL** [comment]
Also, when git merging, file listener is getting triggered while merge process in ongoing, so Git metadata is present in files. The package.yaml and version files are problematic since YamlLoader cannot parse content with these Git temporary annotations.  Example:

 <<<<<<< Updated upstream

**Comment by jbrojdeCTL** [comment]
The exception org.eclipse.jgit.errors.MissingObjectException: Missing unknown 71c93e8b9d64e7a3b9193dde6dbc9825210a9542 seems to be fixed now by commit [CenturyLinkCloud/mdw](https://github.com/CenturyLinkCloud/mdw/commit/69cf6b347af68dda95d002abc3583af3d48a1069)
