### ISSUE TITLE
Newly-added manual task activity causes runtime error

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-studio#9]
Steps to reproduce:
  1. Create a new process.
  2. Drag an AutoformManualTask activity onto the canvas and insert in the flow.
  3. Right-click on the process in the IntelliJ project view and select Run Process.

The following exception is thrown:
```
[(i)20180831.09:52:05.522 p133988419.1 a1.1] Activity started - Start
[(i)20180831.09:52:05.537 p133988419.1 a1.1] Activity completed - completion code null
[(i)20180831.09:52:05.542 p133988419.1 t1.1] Transition initiated from 1 to 3
[(i)20180831.09:52:05.550 p133988419.1 a3.2] Activity started - My Task
[(s)20180831.09:52:05.553 ~101] Failed to execute activity - com.centurylink.mdw.activity.ActivityException
com.centurylink.mdw.activity.ActivityException: Missing attribute: TASK_TEMPLATE
	at com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity.execute(AutoFormManualTaskActivity.java:83)
	at com.centurylink.mdw.workflow.activity.DefaultActivityImpl.execute(DefaultActivityImpl.java:41)
	at com.centurylink.mdw.services.process.BaseActivity.execute(BaseActivity.java:221)
	at com.centurylink.mdw.services.process.BaseActivity.executeTimed(BaseActivity.java:240)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:379)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:612)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvents(ProcessEngineDriver.java:578)
	at com.centurylink.mdw.services.process.InternalEventDriver.run(InternalEventDriver.java:37)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$Work.run(CommonThreadPool.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$ManagedThread.run(CommonThreadPool.java:232)
Caused by: com.centurylink.mdw.activity.ActivityException: Missing attribute: TASK_TEMPLATE
	at com.centurylink.mdw.workflow.activity.task.ManualTaskActivity.createTaskInstance(ManualTaskActivity.java:76)
	at com.centurylink.mdw.workflow.activity.task.AutoFormManualTaskActivity.execute(AutoFormManualTaskActivity.java:60)
	... 12 more
Caused by: com.centurylink.mdw.activity.ActivityException: Missing attribute: TASK_TEMPLATE
	at com.centurylink.mdw.workflow.activity.task.ManualTaskActivity.createTaskInstance(ManualTaskActivity.java:47)
	... 13 more
```

**Comment by naveena-bellamkonda** [comment]
unable to reproduce this

**Comment by donaldoakes** [comment]
Fixed by optionally creating and associating a .task asset when a manual task activity is dragged from the toolbox.
